name: code-style
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - uses: yshui/git-clang-format-lint@v1.7
      if: !startsWith(github.event.ref, 'refs/pull')
      with:
        base: ${{ github.event.ref }}~1
    - uses: yshui/git-clang-format-lint@v1.7
      if: startsWith(github.event.ref, 'refs/pull')
      with:
        base: 
