name: code-style
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - uses: yshui/git-clang-format-lint@v1.7
      with:
        base: ${{ github.base_ref }}
