name: code-style
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo $TERM
      - run: apk add git colordiff
      - run: git format-patch --stdout -1 | colordiff
      - run: git format-patch --stdout -1 | TERM=linux colordiff

