name: code-style
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: echo $TERM
      - run: sudo apt-get update
      - run: sudo apt-get install git-all colordiff
      - run: cd "$GITHUB_WORKSPACE"; git format-patch --stdout -1 | colordiff
      - run: cd "$GITHUB_WORKSPACE"; git format-patch --stdout -1 | TERM=linux colordiff

